dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  directories:
  - node_modules
sudo: required
services:
- docker
env:
  global:
  - secure: DCTC77Q3iqggMQxaMzJ/nTxPapyixKnzQwkROuI7bNX+yBMwg347uClzhyeohHcOJHZ/52FnlUfpBVErCIErAIMWablfXElLkEvububPikop40ietmlVJqDfRQgChF6ip8b+LKa9ISHIE/8fbkDZ79EGG+E+/gWXhGgDTdVEa+jALvzwQt1OSw6vR0OUG/GGEJapMrn+ro+W9Z2IQTUZIqrgFbQhnxVD150NTyP97fFDtr/KypeRAs7xEZRkevobLf/znDQ5uv9JQ5QJNdns/dIZTw9Y+mC+etwkAJR7bFMSbGC7dvN/Z6S775Dwcvqtbvq95rKrkiHLbpZ44A/70o5u9y1pV/VsWeS4YBJnpOdgM97XrzJUq78u0gpJ8tPi4XlilQ6kZoIp2bxxpbgApleL6Uqv/nFKk7xtNpiZXUi60pGqsClUTQy5dcJPsPq0Q7Ddm9vqkMBwYgsQkh+IvnYTsEwwVpEJOjNYU690rZJ4aciFUEWzL8syH9mo5Yyh1J1OAqFAiArOkcTL/v/e2oHi5hIl/zI1Q/lS8cEEmhd/42uFoaRPZ7H7vKVjTroqNp1Zsot/kNYiux7LJ+5clThw+GC1ZaX72gnbKLO2tZMz1VSuPXsZTciZZOEMZr0qsmUs1S7gv3V51HsDsSokqX4WGGsfLqWUaV1KIRblmpw=
  - secure: X8FzdazUOO+GqF5+KARMODaIYt3sBTUdqwZg9x0Hu1WJjd46jPfBKa0o1c/XQC2SOlmgq0tLxMBDpVh+08m9UyKweilV1uhlh453KXT3eU6XTn1Ef+KRV6Yi0z4CKjApVHyw8BkbwG09ZJz4sSv/cv/ocEv5O4fizJFy9Lydt4/rVID7VPEv4jRLVvPWVVPslty/KBdaai9lldDU7Np7+l1MwMbsl4DQH+toO1cm+/symwNZSejshZxMf27jFu1VRPd6IRIl7rN9xfTUyn1c0hT3Se+WM7q9j9kLjpIo9IehRlcrp/wDpelICJGGkE5/p6XfzyFvkaQ2Dti1ohc1Zb3nZmyzT3Ao9EOGjY3qMz7uWUXao17pL4wWBRZOKvSphw8wQM/c3gm3nbADfXsJGgAbTYxL116MA7MMGN6IjDhxW5fnR97y3T3t995JHqRvuhNxyTg7gYnwlduBKzz/DuMJB3tXnNxJnyInFH5DlBrR0ZhwgYeh4eM5mAoyLJ4VarjLyloNg6jfYW4CZYLFy04b4uNiZYBvId/FWXX5HsKETeLGrUPp6g6uk08OT4CnJdjxa+U+4Agg/UAtXZS5f4nNIHwEmtc462qVa2DRR1L4Z6ttrQLwsTnieRHVQ1zwvOVUgrkdKGM30RwxDSfT1PocbgnIWf3WXmnyc1mqpeQ=
