dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  directories:
  - node_modules
sudo: required
services:
- docker
env:
  global:
  - secure: EvXPmfQAMyZz0Mv1iFo1IH5YW43UIllWydJMD+zi1LX7Q6IEyTjlN0VVR4MzOjvK9LPDnQIlhNGGeo3M8Xee9w/1+IOZQDGO72X+ANfOHB7NsNrla5s8SYpqRZLsBURIy/hnfAQ8fxpqHFZZpDoqfLtKRC/GqiKxLzcBbsEP7h6iZzHuzRp53rUoDBMLogCo8+OpIE9rGQmRV2e5Lyywm76WECldyw0UXjSuC1bz1K8TV0dZcxWx/vdvfkoSC97ShhqfEXvl6Z/nw4GKWbgiJN+oDKfWLaWIUixP/ADevjDn02ooOxg2faI7WgHxdhAfF1fkvdYKWfQ46MbPnrKd6XevuDdOfrcbAiNF52rG7GibEWTpGoi4iU8C5W/glEf9SIkoKfebUeejdIYm3xJ8avKeMp/NsPeUhqnxGPr4RGFTjMHs8oCkScu5vD85Uj2Dj8D4PjCsJE1c/VTDQIR7E3plHVnMYRVfZZgQlfKOgUzqW8PyZISvFhr54zsMIsRik4zv4+92PFPnutwkKZvIvGhAkauV2uw9Gq/7AHAF5tv4whyPywk7mdrjY4hHW5bhXzKFyLMEE8lCUuP9ndNEQd4AUNfIBTJjIyrqWRJnCtcij5liGxYH8oyJuwfOPxUpZoi6ZbGhR3aSvYZjcVuSyOjXq+boE6qdoaw3IhV5pxQ=
  - secure: rHRim4qxKO55FVToyBWHPKM1/uD9LfJ5Rcz5rrRQ49FMRq5D3Uu15/0jeunlJt5qX2jt/kMYubZ+MRMM4xynlOEFwP6UdAARAKA+edykVlpF4Bt4vKKdmZ+OOSskmbAfeCdplTVLEO1eznc/qWL1MO63aK/x8VYAG2TIzmAajwAFc4N/EkxVETOQ0oUM6dJTx0UVnwaozcz3RKiwvtCvkOfQcO3McGnS47OiuDgFJ0NruRUTgp43ih0XPDTrDKamFUBwPXB8eHNX6fctaY5cCeMpO5bwNqOqo1XX97eojDyEGeg50JWPhGtAIbnyBjqQ6M1/lhHT/bYGQs43Fe/jFFBTzQ4wSNAtPB56vbAz+kqc9iq3SxLhGa77YBMtI0hdY/vGG/INN8EUo41+f4W+M60PrTjh5gPvwMPjtGdRv3faU92hKNHhUUPXHVbQ0gGvSVQtdjqnIFHKFbHkxfB/dAgUOxMNzPumZqz34j+vmhetG495+EzTYsbY581gPWo/nKLp2PtcmYfE6j3GRRnREU58IG3aCoJcSmEhAu2VdC0V0djIBeLbqTIUVFOqB33kDfWu9mfoYNYeAoVV9OqCNSpecDc2QqBOBpVIqFcOD6gsD0vnPQTqR3QlkLBCBESKWlG6DC/vriJuqkSsqOQ01megnHhtaUWDMg02DXSrz3I=
